---
# =====================================================================
# MySQL 機密情報設定 (サンプル)
# =====================================================================
# 本ファイルを secret.yml にコピーして実際の設定を記述してください。

# データベースのルートパスワード
mysql_root_password: "YourRootPassword123!"

# アプリケーション用データベースとユーザー設定
mysql_app_database: "db_common"

# アプリ用ユーザー
mysql_app_user: "app"
mysql_app_password: "AppPassword123!"

# メンテ用ユーザー
mysql_maintainer_user: "maintainer"
mysql_maintainer_password: "MaintainerPassword123!"
